module.exports={
    PRODUCT_COLLECTION:'product',
    ADMIN_COLLECTION:'admin',
    WISHLIST_COLLECTION:'wishlist',
    USER_COLLECTION:'user',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    ORDER_STATUS_COLLECTION:'status'
}